--Number of "error tuples" in Article: 14
--Number of "error tuples" in Conference: 4591

--Q3a: 
ALTER TABLE inproceedings
ADD area text;

--Q3b:
UPDATE INPROCEEDINGS
SET AREA = 'Database'
WHERE BOOKTITLE = 'SIGMOD Conference' OR BOOKTITLE = 'VLDB' OR BOOKTITLE = 'ICDE' OR BOOKTITLE = 'PODS';

UPDATE INPROCEEDINGS
SET AREA = 'Theory'
WHERE BOOKTITLE = 'STOC' OR BOOKTITLE = 'FOCS' OR BOOKTITLE = 'SODA' OR BOOKTITLE = 'ICALP';

UPDATE INPROCEEDINGS
SET AREA = 'Systems'
WHERE BOOKTITLE = 'SIGCOMM' OR BOOKTITLE = 'ISCA' OR BOOKTITLE = 'HPCA' OR BOOKTITLE = 'PLDI';

UPDATE INPROCEEDINGS
SET AREA = 'ML-AI'
WHERE BOOKTITLE = 'ICML' OR BOOKTITLE = 'NIPS' OR BOOKTITLE = 'AAAI' OR BOOKTITLE = 'IJCAI';

UPDATE INPROCEEDINGS
SET AREA = 'UNKNOWN'
WHERE BOOKTITLE != 'SIGMOD Conference' AND BOOKTITLE != 'VLDB' AND BOOKTITLE != 'ICDE' AND BOOKTITLE != 'PODS'
  AND BOOKTITLE != 'STOC' AND BOOKTITLE != 'FOCS' AND BOOKTITLE != 'SODA' AND BOOKTITLE != 'ICALP'
  AND BOOKTITLE != 'SIGCOMM' AND BOOKTITLE != 'ISCA' AND BOOKTITLE != 'HPCA' AND BOOKTITLE != 'PLDI'
  AND BOOKTITLE != 'ICML' AND BOOKTITLE != 'NIPS' AND BOOKTITLE != 'AAAI' AND BOOKTITLE != 'IJCAI';

--Q3c:
SELECT COUNT(*) FROM ARTICLE
WHERE PUBKEY LIKE 'conf/%'; 

SELECT COUNT(*) FROM INPROCEEDINGS
WHERE PUBKEY LIKE 'journals/%'; 

DELETE FROM ARTICLE
WHERE PUBKEY LIKE 'conf/%';

DELETE FROM INPROCEEDINGS 
WHERE PUBKEY LIKE 'journals/%';
