--Q5A
SELECT '1950~1959 ARTICLE', COUNT(*) FROM ARTICLE
WHERE CAST(YEAR AS INTEGER) >= 1950 AND CAST(YEAR AS INTEGER) <= 1959
UNION
SELECT '1960~1969 ARTICLE', COUNT(*) FROM ARTICLE
WHERE CAST(YEAR AS INTEGER) >= 1960 AND CAST(YEAR AS INTEGER) <= 1969
UNION 
SELECT '1970~1979 ARTICLE', COUNT(*) FROM ARTICLE
WHERE CAST(YEAR AS INTEGER) >= 1970 AND CAST(YEAR AS INTEGER) <= 1979
UNION
SELECT '1980~1989 ARTICLE', COUNT(*) FROM ARTICLE
WHERE CAST(YEAR AS INTEGER) >= 1980 AND CAST(YEAR AS INTEGER) <= 1989
UNION
SELECT '1990~1999 ARTICLE', COUNT(*) FROM ARTICLE
WHERE CAST(YEAR AS INTEGER) >= 1990 AND CAST(YEAR AS INTEGER) <= 1999
UNION
SELECT '2000~2009 ARTICLE', COUNT(*) FROM ARTICLE
WHERE CAST(YEAR AS INTEGER) >= 2000 AND CAST(YEAR AS INTEGER) <= 2009
UNION
SELECT 'After 2010 ARTICLE', COUNT(*) FROM ARTICLE
WHERE CAST(YEAR AS INTEGER) >= 2010
UNION
SELECT '1950~1959 INPROCEEDINGS', COUNT(*) FROM INPROCEEDINGS
WHERE CAST(YEAR AS INTEGER) >= 1950 AND CAST(YEAR AS INTEGER) <= 1959
UNION
SELECT '1960~1969 INPROCEEDINGS', COUNT(*) FROM INPROCEEDINGS
WHERE CAST(YEAR AS INTEGER) >= 1960 AND CAST(YEAR AS INTEGER) <= 1969
UNION
SELECT '1970~1979 INPROCEEDINGS', COUNT(*) FROM INPROCEEDINGS
WHERE CAST(YEAR AS INTEGER) >= 1970 AND CAST(YEAR AS INTEGER) <= 1979
UNION
SELECT '1980~1989 INPROCEEDINGS', COUNT(*) FROM INPROCEEDINGS
WHERE CAST(YEAR AS INTEGER) >= 1980 AND CAST(YEAR AS INTEGER) <= 1989
UNION
SELECT '1990~1999 INPROCEEDINGS', COUNT(*) FROM INPROCEEDINGS
WHERE CAST(YEAR AS INTEGER) >= 1990 AND CAST(YEAR AS INTEGER) <= 1999
UNION
SELECT '2000~2009 INPROCEEDINGS', COUNT(*) FROM INPROCEEDINGS
WHERE CAST(YEAR AS INTEGER) >= 2000 AND CAST(YEAR AS INTEGER) <= 2009
UNION
SELECT 'After 2010 INPROCEEDINGS', COUNT(*) FROM INPROCEEDINGS
WHERE CAST(YEAR AS INTEGER) >= 2010;


--Q5b
SELECT '2010~ Database', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Database' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2010)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 2010)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2010))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '2000~2009 Database', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Database' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2000 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 2009)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 2000 AND CAST(ARTICLE.YEAR AS INTEGER) <= 2009)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2000 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 2009))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1990~1999 Database', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Database' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1990 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1999)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1990 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1999)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1990 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1999))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1980~1989 Database', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Database' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1980 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1989)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1980 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1989)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1980 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1989))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1970~1979 Database', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Database' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1970 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1979)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1970 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1979)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1970 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1979))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1960~1969 Database', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Database' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1960 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1969)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1960 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1969)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1960 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1969))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1950~1959 Database', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Database' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1950 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1959)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1950 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1959)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1950 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1959))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB

UNION

SELECT '2010~ Theory', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Theory' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2010)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 2010)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2010))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '2000~2009 Theory', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Theory' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2000 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 2009)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 2000 AND CAST(ARTICLE.YEAR AS INTEGER) <= 2009)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2000 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 2009))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1990~1999 Theory', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Theory' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1990 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1999)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1990 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1999)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1990 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1999))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1980~1989 Theory', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Theory' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1980 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1989)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1980 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1989)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1980 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1989))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1970~1979 Theory', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Theory' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1970 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1979)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1970 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1979)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1970 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1979))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1960~1969 Theory', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Theory' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1960 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1969)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1960 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1969)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1960 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1969))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1950~1959 Theory', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Theory' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1950 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1959)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1950 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1959)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1950 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1959))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB

UNION

SELECT '2010~ Systems', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Systems' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2010)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 2010)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2010))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '2000~2009 Systems', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Systems' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2000 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 2009)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 2000 AND CAST(ARTICLE.YEAR AS INTEGER) <= 2009)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2000 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 2009))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1990~1999 Systems', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Systems' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1990 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1999)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1990 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1999)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1990 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1999))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1980~1989 Systems', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Systems' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1980 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1989)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1980 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1989)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1980 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1989))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1970~1979 Systems', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Systems' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1970 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1979)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1970 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1979)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1970 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1979))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1960~1969 Systems', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Systems' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1960 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1969)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1960 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1969)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1960 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1969))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1950~1959 Systems', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'Systems' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1950 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1959)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1950 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1959)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1950 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1959))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB

UNION

SELECT '2010~ ML-AI', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'ML-AI' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2010)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 2010)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2010))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '2000~2009 ML-AI', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'ML-AI' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2000 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 2009)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 2000 AND CAST(ARTICLE.YEAR AS INTEGER) <= 2009)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 2000 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 2009))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1990~1999 ML-AI', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'ML-AI' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1990 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1999)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1990 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1999)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1990 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1999))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1980~1989 ML-AI', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'ML-AI' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1980 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1989)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1980 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1989)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1980 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1989))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1970~1979 ML-AI', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'ML-AI' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1970 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1979)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1970 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1979)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1970 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1979))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1960~1969 ML-AI', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'ML-AI' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1960 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1969)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1960 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1969)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1960 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1969))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB
UNION
SELECT '1950~1959 ML-AI', CASE
	WHEN COUNT(*) = 0
		THEN 0
		ELSE SUM(CNTCOLLAB) / COUNT(*)
	END
FROM

(SELECT TAB2.AUTH AS AUTHNAME, COUNT(DISTINCT AAAI.AUTH) AS CNTCOLLAB
FROM
(SELECT TAB1.AUTH AS AUTH, AUTHORSHIP.PUBKEY AS PK
FROM
	(SELECT DISTINCT AUTHORSHIP.AUTHOR AS AUTH
	FROM AUTHORSHIP
	JOIN INPROCEEDINGS
	ON AUTHORSHIP.PUBKEY = INPROCEEDINGS.PUBKEY AND INPROCEEDINGS.AREA = 'ML-AI' 
	AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1950 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1959)
	AS TAB1
JOIN AUTHORSHIP
ON TAB1.AUTH = AUTHORSHIP.AUTHOR)
AS TAB2

JOIN

((SELECT ARTICLE.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN ARTICLE
ON ARTICLE.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(ARTICLE.YEAR AS INTEGER) >= 1950 AND CAST(ARTICLE.YEAR AS INTEGER) <= 1959)
UNION
(SELECT INPROCEEDINGS.PUBKEY AS PK, AUTHORSHIP.AUTHOR AS AUTH
FROM AUTHORSHIP
JOIN INPROCEEDINGS
ON INPROCEEDINGS.PUBKEY = AUTHORSHIP.PUBKEY AND CAST(INPROCEEDINGS.YEAR AS INTEGER) >= 1950 AND CAST(INPROCEEDINGS.YEAR AS INTEGER) <= 1959))
AS AAAI

ON TAB2.PK = AAAI.PK AND TAB2.AUTH <> AAAI.AUTH
GROUP BY TAB2.AUTH)
AS TTTAB;

